#[derive(Debug)]
pub enum Instruction {
    NOP,
    ClearScreen,
    Jump(u16),
    SetRI(u8, u8),
    AddRI(u8, u8),
    SetX(u16),
    Draw(u8, u8, u8),
    Call(u16),
    Return,
    SkipIEQ(u8, u8),
    SkipINEQ(u8, u8),
    SkipREQ(u8, u8),
    SkipRNEQ(u8, u8),
    SetRR(u8, u8),
    OrRR(u8, u8),
    AndRR(u8, u8),
    XorRR(u8, u8),
    AddRR(u8, u8),
    SubAB(u8, u8),
    SubBA(u8, u8),
    ShiftRightRR(u8, u8),
    ShiftLeftRR(u8, u8),
    JumpOffset(u16),
    Random(u8, u8),
    SkipKeyEQ(u8),
    SkipKeyNEQ(u8),
    SetRDelay(u8),
    SetDelayR(u8),
    SetSoundR(u8),
    AddXR(u8),
    GetKey(u8),
    SetXFontR(u8),
    StoreDecimalR(u8),
    Store(u8),
    Load(u8),
    Data(u8, u8) // default if no other opcode matched
}